# Generated by Django 5.1.1 on 2024-10-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
